CREATE TABLE CURSO(
	ID_CURSO SERIAL PRIMARY KEY,
	NOME VARCHAR(255)
);

CREATE TABLE MODULO(
	ID_MODULO SERIAL PRIMARY KEY,
	NOME VARCHAR(255)
);


CREATE TABLE TURMA(
	ID_TURMA SERIAL PRIMARY KEY,
	NOME VARCHAR(255),
	ID_CURSO INT,
	ID_MODULO INT,
	FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
	FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO)
);

CREATE TABLE ESTUDANTE(
	ID_ESTUDANTE SERIAL PRIMARY KEY,
	NOME VARCHAR(255),
	CPF VARCHAR,
	STATUS VARCHAR;
	ID_TURMA INT,
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
);

CREATE TABLE PESSOA_FACILITADORA(
	ID_PESSOA_FACILITADORA SERIAL PRIMARY KEY,
	NOME VARCHAR(255),
	CPF VARCHAR,
	FRENTE VARCHAR(255)
);

CREATE TABLE TURMA_PESSOA_FACILITADORA(
	ID_TURMA_PESSOA_FACILITADORA SERIAL PRIMARY KEY,
	ID_PESSOA_FACILITADORA INT,
	ID_TURMA INT,
	FOREIGN KEY (ID_PESSOA_FACILITADORA) REFERENCES PESSOA_FACILITADORA(ID_PESSOA_FACILITADORA),
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
);

/*Para povoar as tabelas usamos 3 arquivos CSV, 2 deles que foram compartilhados nas aulas mas com alterações e 1 desenvolvido pelo último código
apresentado no trabalho em grupo do 2 módulo*/

/*Para povoar a tabela estudante foi usado o seguinte código(O arquivo vai estar na aba de scripts no GITHUB)*/

COPY ESTUDANTE (ID_ESTUDANTE,NOME,CPF,ID_TURMA) FROM 'AQUI VOCÊ COLOCA O DIRETÓRIO QUE ESTA O ARQUIVO\NOMEARQUIVO.CSV' DELIMITER ',' CSV HEADER

/*Para povoar a tabela curso foi usado o mesmo código*/

COPY CURSO (ID_CURSO,NOME) FROM 'AQUI VOCÊ COLOCA O DIRETÓRIO QUE ESTA O ARQUIVO\NOMEARQUIVO.CSV' DELIMITER ',' CSV HEADER

/*Para povoar a tabela pessoa_facilitadora foi usado o mesmo código mas com a diferença que o delimitador não é virgula, mas sim ponto e virgula.
Após fazer as alterações nos arquivos CSV sempre dava erro, então presumi que o problema era o demilitador que estava errado, por isso nos outros
2 CSV teve alteração para , e nesse ficou ;*/

COPY PESSOA_FACILITADORA (ID_PESSOA_FACILITADORA, NOME, CPF, FRENTE) FROM 'AQUI VOCÊ COLOCA O DIRETÓRIO QUE ESTA O ARQUIVO\NOMEARQUIVO.CSV' DELIMITER ';' CSV HEADER



/*Para povoar a tabala módulo, usamos o código insert, ficando assim*/

INSERT INTO MODULO ('ID_MODULO','NOME') VALUES (1,'MODULO 1')
INSERT INTO MODULO ('ID_MODULO','NOME') VALUES (2,'MODULO 2')
INSERT INTO MODULO ('ID_MODULO','NOME') VALUES (3,'MODULO 3')
INSERT INTO MODULO ('ID_MODULO','NOME') VALUES (4,'MODULO 4')
INSERT INTO MODULO ('ID_MODULO','NOME') VALUES (5,'MODULO 5')

/*O ID precisa ficar sem aspas para ser do tipo inteiro já o nome está no tipo VARCHAR*/

/*Para povoar a tabela turma usamos também o código insert*/

INSERT INTO TURMA ('ID_TURMA','NOME','ID_CURSO','ID_MODULO') VALUES (1,'DATA_ANALYTICS 01',1,1)
INSERT INTO TURMA ('ID_TURMA','NOME','ID_CURSO','ID_MODULO') VALUES (1,'DATA_ANALYTICS 02',1,4)
INSERT INTO TURMA ('ID_TURMA','NOME','ID_CURSO','ID_MODULO') VALUES (1,'FULL_STACK 01',4,3)
INSERT INTO TURMA ('ID_TURMA','NOME','ID_CURSO','ID_MODULO') VALUES (1,'BAKC_END',2,2)

/*Para povoar a tabela TURMA_PESSOA_fACILITADORA*/

INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (1,5,2)
INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (2,4,2)
INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (3,6,1)
INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (4,1,1)
INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (5,2,3)
INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (6,3,3)
INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (7,2,4)
INSERT INTO TURMA_PESSOA_FACILITADORA ('ID_TURMA_PESSOA_FACILITADORA','ID_PESSOA_FACILTIADORA','ID_TURMA') VALUES (8,4,4)


/*Após criar as tabelas, foi dessa forma que povoamos as tabelas.*/

/*Mas acabamos esquecendo de um detalhe, que era para responder a pergunta sobre taxa de evasão, então criamos na tabela ESTUDANTE,
uma nova coluna com o STATUS, para saber se ele está ativo ou inativo.*/

ALTER TABLE ESTUDANTE
ADD COLUMN STATUS VARCHAR(10)

/*E para povoar a coluna verificamos o STATUS de todos os alunos e adcionamos com*/

UPDATE ESTUDANTE
SET STATUS = 'INATIVO'
WHERE ID_ESTUDANTE = 2 /*Tivemos que fazer esse update estudante por estudante, para substituir o status do estudante é só mudar o ID na linha WHERE*/

UPDATE ESTUDANTE
SET STATUS = 'ATIVO'
WHERE ID_ESTUDANTE = 1 /*Tivemos que fazer esse update estudante por estudante, para substituir o status do estudante é só mudar o ID na linha WHERE*/
